apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../openpracticelibrary/content-api/base
patchesStrategicMerge:
- patchCM.yaml
images:
- name: quay.io/openpracticelibrary/opl-content-api
  newTag: v0.1.0-beta
