apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-jnlp 
spec:
  ports:
  - name: agent
    nodePort: 0
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    name: {{ .Values.appName }}
  sessionAffinity: None
  type: ClusterIP

