apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata:
  name: {{ .Values.appName }}_edit
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ .Values.appName }}
