apiVersion: route.openshift.io/v1 
kind: Route
metadata:
  annotations:
  name: {{ .Values.appName }}
spec:
  host: ""
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.appName }}
    weight: 100
status:
  ingress: [] 
