apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}
  annotations:
{{- if eq .Values.auth.enabled true }}
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ .Values.appName }}"}}'
{{- end }}
