namespace: fe-enablement-dev
commonLabels:
  variant: dev
  relation: fe-enablement
resources:
- ../../openpracticelibrary/api-gateway/overlays/development/
- ../../openpracticelibrary/media-service/overlays/development/
- ./content-api/
patchesStrategicMerge:
- patchMediaServiceCM.yaml
- patchRoutes.yaml
