apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opl-staging
commonLabels:
  variant: staging
resources:
- ../../base
patchesStrategicMerge:
- ./patchRoute.yaml
images:
- name: quay.io/openpracticelibrary/opl-api-gateway
  newTag: v0.1.0-beta
