apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opl-dev
commonLabels:
  variant: dev
resources:
- ../../base
patchesStrategicMerge:
- patchRoute.yaml
images:
- name: quay.io/openpracticelibrary/opl-fe
  newTag: 6566bd9c9cc4cdf4e8a9d666adb6b3b34e36e2ae
