apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opl-dev
commonLabels:
  variant: dev
resources:
- ../../base
patchesStrategicMerge:
- patchRoute.yaml
images:
- name: quay.io/openpracticelibrary/opl-fe
  newTag: 85a5eb6013e6b0ea69b2fd2c9df04ae84f757bd0
