apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opl-dev
commonLabels:
  variant: dev
resources:
- ../../base
images:
- name: quay.io/openpracticelibrary/opl-fe
  newTag: df89ee06d87a3deec1fd4842d33c8adf3e601de8
