namespace: opl-staging
commonLabels:
  variant: staging
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- patchCM.yaml
- patchRoute.yaml
images:
- name: quay.io/openpracticelibrary/opl-content-api
  newTag: v.0.1.1-beta
