{{- if .Values.argodeploys }}
{{- range $key := .Values.argodeploys }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: {{ $.Values.app_name }}-{{ .env }}
  namespace: {{ $.Values.namespace }}
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .server | default "https://kubernetes.default.svc" }}
  project: {{ .project | default "default" }}
  source:
    helm:
      releaseName: {{ .releasename | default $.Values.app_name }}
      valueFiles: 
      - {{ .valueFile }}
    path: {{ .path }} 
    repoURL: {{ .repoUrl }}
    targetRevision: {{ .targetRevision | default "master" }}
{{- end }}
{{- end }}

