apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opl-dev
commonLabels:
  variant: dev
resources:
- ../../base
images:
- name: quay.io/openpracticelibrary/opl-media-service
  newTag: a40124d71e50a39cdbb7c0f9b3c72adbda05fae1
