apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opl-dev
commonLabels:
  variant: dev
resources:
- ../../base
- route.yaml
images:
- name: quay.io/openpracticelibrary/opl-media-service
  newTag: d5010a87879fd7f9ed0f43c398dc17fb28fa224d
