apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opl-dev
commonLabels:
  variant: dev
resources:
- ../../base
patchesStrategicMerge:
- patchRoute.yaml
images:
- name: quay.io/openpracticelibrary/opl-media-service
  newTag: 43cab196c8b7a7ebdc1359dd62ec3d665f98a6fe
