apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opl-staging
commonLabels:
  variant: staging
resources:
- ../../base
images:
- name: quay.io/openpracticelibrary/opl-media-service
  newTag: latest
