namespace: opl-dev
commonLabels:
  variant: dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- patchCM.yaml
images:
- name: quay.io/openpracticelibrary/opl-content-api
  newTag: bf3dcbf58c84a8d2c9b06ec1c805011bf9649c56
