namespace: opl-dev
commonLabels:
  variant: dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- patchCM.yaml
- patchRoute.yaml
images:
- name: quay.io/openpracticelibrary/opl-content-api
  newTag: 00f550b6fe9c8589f6f9d684b54ff30b44ed01c9
