{{- if .Values.builds }}
{{- with .Values.builds }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: "{{ $.Values.app_name }}-pipeline"
  namespace: {{ .namespace | default $.Values.cicd_namespace | quote }}
spec:
  nodeSelector: {}
  runPolicy: {{ .run_policy | default "Serial" | quote }}
  triggers:
    - type: {{ .trigger_type }}
      {{ .trigger_type | lower }}:
        secretReference:
          name: {{ .secret_name }}
    - type: "ConfigChange"
  source:
    contextDir: {{ .source_context_dir | default "" | quote }}
    git:
      uri: "{{ .source_repo }}"
      ref: {{ .source_repo_ref | default "master" | quote }}
    type: Git
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile"
{{- if .env_vars }}
      env:
        {{- range $key, $val := .env_vars }}
        - name: {{ $key | upper }}
          value: {{ $val | quote }}
      {{- end }}
{{- end }}
status:
  lastVersion: 0
{{- end }}
{{- end }}


