{{- if .Values.configmap }}
{{- range .Values.configmap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.dev_namespace }}
data:
{{ toYaml .config_data | indent 2}}
{{- end }}
{{- end }}

