{{- if .Values.imagestreams.enabled }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: "{{ .Values.app_name }}"
  namespace: "{{ .Values.dev_namespace }}"
  labels:
    app: {{ .Values.app_name }}
    chart: {{ template "opl-fe.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec: {}
{{- end }}


