apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opl-dev
commonLabels:
  variant: dev
resources:
- ../../base
patchesStrategicMerge:
- ./patchRoute.yaml
images:
- name: quay.io/openpracticelibrary/opl-api-gateway
  newTag: 173b9528f585f6f5c6bfa7a4561d4971d46ea87c
