apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opl-dev
commonLabels:
  variant: dev
resources:
- ../../base
images:
- name: quay.io/openpracticelibrary/opl-api-gateway
  newTag: 94fa0e1b77e84ac34adf115dbdf9d088882574b5
