apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: github-tag-task
spec:
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: github-tag
      image: quay.io/openpracticelibrary/toolbox:latest
      workingDir: /workspace/repo
      script: |
        #!/usr/bin/env bash
        git config --global user.email "shahein@redhat.com"
        git config --global user.name "GitHub Actions"
        SHA=$(git rev-parse --short HEAD)
        echo $SHA
        git tag $SHA
        git push origin --tags