apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: trigger-staging-deploy-taskrun
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  taskRef:
    name: trigger-staging-deploy